services:
  springboot:
    build: ./shapes
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ushapes
      SPRING_DATASOURCE_USERNAME: ushapes
      SPRING_DATASOURCE_PASSWORD: ushapes123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true

  postgres:
    image: postgres:17.4-alpine3.20
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_DB: ushapes
      POSTGRES_USER: ushapes
      POSTGRES_PASSWORD: ushapes123
    ports:
      - "5432:5432"
    volumes:
      - pg_data_persistente_shapes:/var/lib/postgresql/data

  bgremover:
    build: ./bgRemover
    container_name: bg_remover
    ports:
      - "5000:5000"

  frontend:
    build: ../frontend
    container_name: frontend_bun
    ports:
      - "5173:5173"
    depends_on:
      - springboot
      - bgremover

volumes:
  pg_data_persistente_shapes:
